networks:
  default:
    name: home-media-server
    external: true

services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - WEBUI_PORTS=8080/tcp,8080/udp
      - VPN_ENABLED=true
      - VPN_PROVIDER=pia
      - VPN_LAN_NETWORK=192.168.0.0/24
      - VPN_LAN_LEAK_ENABLED=false
      - VPN_AUTO_PORT_FORWARD=true
      - VPN_KEEP_LOCAL_DNS=false
      - VPN_FIREWALL_TYPE=auto
      - VPN_HEALTHCHECK_ENABLED=true
      - VPN_PIA_USER=$OPENVPN_USER
      - VPN_PIA_PASS=$OPENVPN_PASSWORD
      - VPN_PIA_PREFERRED_REGION=ca
      - VPN_PIA_DIP_TOKEN=no
      - VPN_PIA_PORT_FORWARD_PERSIST=false
      - PRIVOXY_ENABLED=false
      - UNBOUND_ENABLED=false
    volumes:
      - ./configs/qbittorrent:/config
      - $MEDIADIR:/data
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped

  bazarr: #subtitle grabber
    container_name: bazarr
    image: ghcr.io/hotio/bazarr
    ports:
      - "6767:6767"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - WEBUI_PORTS=6767/tcp,6767/udp
    volumes:
      - ./configs/bazarr:/config
      - $MEDIADIR:/data/media
    restart: unless-stopped

  caddy:
    container_name: caddy
    image: ghcr.io/hotio/caddy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - CUSTOM_BUILD=/config/caddy_linux_amd64_custom
    volumes:
      - ./configs/caddy:/config
    restart: unless-stopped

  overseerr: #media requesting tool
    container_name: overseerr
    image: ghcr.io/hotio/overseerr
    ports:
      - "5055:5055"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - WEBUI_PORTS=5055/tcp,5055/udp
    volumes:
      - ./configs/overseerr:/app/config
    restart: unless-stopped

  plex: # Media Server
    container_name: plex
    image: ghcr.io/hotio/plex
    ports:
      - 32400:32400
    logging:
      driver: json-file
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=002
      - PLEX_CLAIM_TOKEN=$PLEX_CLAIM
      - PLEX_BETA_INSTALL=false
      - PLEX_PURGE_CODECS=false
    volumes:
      - ./configs/plex:/config:rw
      - $PLEXMEDIA:/data/media:rw
      - /tmp:/transcode:rw
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=$TZ
    ports:
      - "8191:8191"
    restart: unless-stopped

  prowlarr: #indexer manager for Sonarr & Radarr
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - "9696:9696"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - WEBUI_PORTS=9696/tcp,9696/udp
    volumes:
      - ./configs/prowlarr:/config
    restart: unless-stopped

  radarr: #movie search agent
    container_name: radarr
    image: ghcr.io/hotio/radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - WEBUI_PORTS=7878/tcp,7878/udp
    volumes:
      - ./configs/radarr:/config
      - $MEDIADIR:/data
    restart: unless-stopped

  sonarr: #TV show search agent
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - WEBUI_PORTS=8989/tcp,8989/udp
    volumes:
      - ./configs/sonarr:/config
      - $MEDIADIR:/data
    restart: unless-stopped

  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=ServerNode
    volumes:
      - ./configs/tdarr/server:/app/server
      - ./configs/tdarr/configs:/app/configs
      - ./configs/tdarr/logs:/app/logs
      - /media/arnaud/hdd/media-server/media:/media
      - ./configs/tdarr/transcode_cache:/temp
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  # tautulli: #plex monitoring
  #   container_name: tautulli
  #   image: ghcr.io/hotio/tautulli
  #   ports:
  #     - "8181:8181"
  #   environment:
  #     - PUID=$PUID
  #     - PGID=$PGID
  #     - UMASK=002
  #     - TZ=$TZ
  #     - WEBUI_PORTS=8181/tcp,8181/udp
  #   volumes:
  #     - ./configs/tautulli:/config
  #   restart: unless-stopped
  
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    environment:
      - TZ=$TZ
      - DEFAULT_COLOR_SCHEME=dark
      - DISABLE_ANALYTICS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/homarr/configs:/app/data/configs
      - ./configs/homarr/icons:/app/public/icons
      - ./configs/homarr/data:/data
    ports:
      - '7575:7575'

  dash:
    image: mauricenino/dashdot:latest
    container_name: dash
    restart: unless-stopped
    privileged: true
    ports:
      - '3001:3001'
    environment:
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_WIDGET_LIST=cpu,storage,ram,network
      - DASHDOT_PAGE_TITLE=Home Server
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
      - DASHDOT_ACCEPT_OOKLA_EULA=true
      - DASHDOT_SPEED_TEST_INTERVAL=720 # 12h
      - DASHDOT_FS_DEVICE_FILTER=nvme0n1
    volumes:
      - /:/mnt/host:ro
