networks:
  default:
    name: home-plex
    external: true

services:
  gluetun:
    container_name: vpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      # qbittorent
      - 8080:8080

      # unknown
      # - 6881:6881
      # - 6881:6881/udp

      # arr suite
      - 6767:6767
      - 7878:7878
      - 8989:8989
      - 9696:9696

      # overseer
      - 5055:5055
    volumes:
      # - ./configs/gluetun/vpn.conf:/gluetun/vpn.conf:ro
      - ./configs/gluetun:/gluetun
    # environment:
    #   - VPN_SERVICE_PROVIDER=custom
    #   - VPN_TYPE=openvpn
    #   - OPENVPN_CUSTOM_CONFIG=/gluetun/vpn.conf
    #   - OPENVPN_USER=username
    #   - OPENVPN_PASSWORD=password
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=$OPENVPN_USER
      - OPENVPN_PASSWORD=$OPENVPN_PASSWORD
      - SERVER_REGIONS=CA Montreal,CA Ontario,CA Toronto
      - FIREWALL_OUTBOUND_SUBNETS=172.17.0.0/16
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - ./configs/qbittorrent:/config
      - $MEDIADIR:/data
    restart: unless-stopped

  bazarr: #subtitle grabber
    container_name: bazarr
    image: ghcr.io/hotio/bazarr
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - WEBUI_PORTS=6767/tcp,6767/udp
    volumes:
      - ./configs/lidarr:/config
      - $MEDIADIR/media:/data/media
    restart: unless-stopped

  overseerr: #media requesting tool
    container_name: overseerr
    image: ghcr.io/hotio/overseerr
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - WEBUI_PORTS=5055/tcp,5055/udp
    volumes:
      - ./configs/overseerr:/app/config
    restart: unless-stopped

  plex: # Media Server
    container_name: plex
    image: ghcr.io/hotio/plex
    ports:
      - 32400:32400
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=002
      - PLEX_CLAIM_TOKEN=$PLEX_CLAIM
      - PLEX_BETA_INSTALL=false
      - PLEX_PURGE_CODECS=false
      # - PLEX_ADVERTISE_URL=$PLEX_ADVERTISE_URL
      # - PLEX_ADVERTISE_URL=http://172.19.0.5:32400
      # - ADVERTISE_IP=$PLEX_ADVERTISE_IP
      # - PLEX_PASS=$PLEX_PASS
    volumes:
      - ./configs/plex:/config:rw
      - $PLEXMEDIA:/data/media:rw
      - /tmp:/transcode:rw
    devices:
      - /dev/dri:/dev/dri #required for Synology users
    # network_mode: "host"

  prowlarr: #indexer manager for Sonarr & Radarr
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - WEBUI_PORTS=9696/tcp,9696/udp
    volumes:
      - ./configs/prowlarr:/config
    restart: unless-stopped

  radarr: #movie search agent
    container_name: radarr
    image: ghcr.io/hotio/radarr
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - WEBUI_PORTS=7878/tcp,7878/udp
    volumes:
      - ./configs/radarr:/config
      - $MEDIADIR:/data
    restart: unless-stopped

  sonarr: #TV show search agent
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - WEBUI_PORTS=8989/tcp,8989/udp
    volumes:
      - ./configs/sonarr:/config
      - $MEDIADIR:/data
    restart: unless-stopped

  # tautulli: #plex monitoring
  #   container_name: tautulli
  #   image: ghcr.io/hotio/tautulli
  #   ports:
  #     - "8181:8181"
  #   environment:
  #     - PUID=$PUID
  #     - PGID=$PGID
  #     - UMASK=002
  #     - TZ=$TZ
  #     - WEBUI_PORTS=8181/tcp,8181/udp
  #   volumes:
  #     - ./configs/tautulli:/config
  #   restart: unless-stopped