networks:
  default:
    name: home-media-server
    external: true

services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - WEBUI_PORTS=8080/tcp,8080/udp
      - VPN_ENABLED=true
      - VPN_PROVIDER=pia
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_LAN_LEAK_ENABLED=false
      - VPN_AUTO_PORT_FORWARD=true
      - VPN_KEEP_LOCAL_DNS=false
      - VPN_FIREWALL_TYPE=auto
      - VPN_HEALTHCHECK_ENABLED=true
      - VPN_PIA_USER=$OPENVPN_USER
      - VPN_PIA_PASS=$OPENVPN_PASS
      - VPN_PIA_PREFERRED_REGION=ca
      - VPN_PIA_DIP_TOKEN=no
      - VPN_PIA_PORT_FORWARD_PERSIST=false
      - PRIVOXY_ENABLED=false
      - UNBOUND_ENABLED=false
    volumes:
      - ./configs/qbittorrent:/config
      - $MEDIADIR:/data
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped

  bazarr: #subtitle grabber
    container_name: bazarr
    image: ghcr.io/hotio/bazarr
    ports:
      - "6767:6767"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - WEBUI_PORTS=6767/tcp,6767/udp
    volumes:
      - ./configs/lidarr:/config
      - $MEDIADIR/media:/data/media
    restart: unless-stopped

  overseerr: #media requesting tool
    container_name: overseerr
    image: ghcr.io/hotio/overseerr
    ports:
      - "5055:5055"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - WEBUI_PORTS=5055/tcp,5055/udp
    volumes:
      - ./configs/overseerr:/app/config
    restart: unless-stopped

  plex: # Media Server
    container_name: plex
    image: ghcr.io/hotio/plex
    ports:
      - 32400:32400
    logging:
      driver: json-file
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=002
      - PLEX_CLAIM_TOKEN=$PLEX_CLAIM
      - PLEX_BETA_INSTALL=false
      - PLEX_PURGE_CODECS=false
    volumes:
      - ./configs/plex:/config:rw
      - $PLEXMEDIA:/data/media:rw
      - /tmp:/transcode:rw
    restart: unless-stopped

  prowlarr: #indexer manager for Sonarr & Radarr
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - "9696:9696"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - WEBUI_PORTS=9696/tcp,9696/udp
    volumes:
      - ./configs/prowlarr:/config
    restart: unless-stopped

  radarr: #movie search agent
    container_name: radarr
    image: ghcr.io/hotio/radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - WEBUI_PORTS=7878/tcp,7878/udp
    volumes:
      - ./configs/radarr:/config
      - $MEDIADIR:/data
    restart: unless-stopped

  sonarr: #TV show search agent
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - WEBUI_PORTS=8989/tcp,8989/udp
    volumes:
      - ./configs/sonarr:/config
      - $MEDIADIR:/data
    restart: unless-stopped

  # tautulli: #plex monitoring
  #   container_name: tautulli
  #   image: ghcr.io/hotio/tautulli
  #   ports:
  #     - "8181:8181"
  #   environment:
  #     - PUID=$PUID
  #     - PGID=$PGID
  #     - UMASK=002
  #     - TZ=$TZ
  #     - WEBUI_PORTS=8181/tcp,8181/udp
  #   volumes:
  #     - ./configs/tautulli:/config
  #   restart: unless-stopped